package com.cnksi.kconf.controller.vo;

import com.cnksi.kcore.web.KWebQueryVO; 
import com.cnksi.kcore.web.api.KQuery; 
/**
 * Generated by JFinal.
 */
@KQuery(sql = "SELECT * from k_department  ") 
public class DepartmentQuery extends KWebQueryVO {
}
