package com.cnksi.kconf.controller.vo;

import com.cnksi.kcore.web.KWebQueryVO;
import com.cnksi.kcore.web.api.KQuery;
import com.cnksi.kcore.web.api.KQueryParam;

/**
 * Generated by JFinal.
 */
@KQuery(sql = "SELECT u.*,r.rname,r.rid FROM k_user u LEFT JOIN k_department d ON u.did =d.did LEFT JOIN k_user_role ur on ur.uid = u.uid LEFT JOIN k_role r on r.rid = ur.rid")
public class UserQuery extends KWebQueryVO {
	/**
	 * 姓名
	 */
	@KQueryParam(colName = "uname", op = "like")
	private String uname;

	/**
	 * 手机号
	 */
	@KQueryParam(colName = "u.tel", op = "like")
	private String tel;

	/**
	 * 所属部门
	 */
	@KQueryParam(colName = "u.did", op = "=")
	private String deptid;

	/**
	 * 用户账号
	 */
	@KQueryParam(colName = "u.uaccount", op = "like")
	private String uaccount;

	public UserQuery() {
		addFilter("u.enabled", "=", "0");
	}

	public String getDeptid() {
		return deptid;
	}

	public void setDeptid(String deptid) {
		this.deptid = deptid;
	}

	public String getUname() {
		return uname;
	}

	public void setUname(String uname) {
		this.uname = uname;
	}

	public String getTel() {
		return tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getUaccount() {
		return uaccount;
	}

	public void setUaccount(String uaccount) {
		this.uaccount = uaccount;
	}

}
