package com.cnksi.app.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("card", "id", Card.class);
		arp.addMapping("card_copy", "id", CardCopy.class);
		arp.addMapping("card_item", "id", CardItem.class);
		arp.addMapping("card_item_type", "id", CardItemType.class);
		arp.addMapping("card_standard", "id", CardStandard.class);
		arp.addMapping("card_type", "id", CardType.class);
		arp.addMapping("count_device", "id", CountDevice.class);
		arp.addMapping("count_task", "id", CountTask.class);
		arp.addMapping("device_field", "id", DeviceField.class);
		arp.addMapping("device_field_value", "id", DeviceFieldValue.class);
		arp.addMapping("device_img", "id", DeviceImg.class);
		arp.addMapping("device_type", "id", DeviceType.class);
		arp.addMapping("doc_field", "id", DocField.class);
		arp.addMapping("doc_field_value", "id", DocFieldValue.class);
		arp.addMapping("doc_file", "id", DocFile.class);
		arp.addMapping("doc_group_value", "id", DocGroupValue.class);
		arp.addMapping("pms_bdz", "id", PmsBdz.class);
		arp.addMapping("pms_device", "id", PmsDevice.class);
		arp.addMapping("pms_dict", "id", PmsDict.class);
		arp.addMapping("pms_spacing", "id", PmsSpacing.class);
		arp.addMapping("pro_milestone", "id", ProMilestone.class);
		arp.addMapping("pro_progress", "id", ProProgress.class);
		arp.addMapping("pro_project", "id", ProProject.class);
		arp.addMapping("pro_project_attachment", "id", ProProjectAttachment.class);
		arp.addMapping("pro_project_attachment_image", "id", ProProjectAttachmentImage.class);
		arp.addMapping("pro_project_scal", "id", ProProjectScal.class);
		arp.addMapping("rel_device_issue", "id", RelDeviceIssue.class);
		arp.addMapping("rel_device_task", "id", RelDeviceTask.class);
		arp.addMapping("result_issue", "id", ResultIssue.class);
		arp.addMapping("result_issue_important", "id", ResultIssueImportant.class);
		arp.addMapping("result_issue_log", "id", ResultIssueLog.class);
		arp.addMapping("result_item", "id", ResultItem.class);
		arp.addMapping("result_item_copy", "id", ResultItemCopy.class);
		arp.addMapping("result_signname", "id", ResultSignname.class);
		arp.addMapping("supervise", "id", Supervise.class);
		arp.addMapping("sys_config", "id", SysConfig.class);
		arp.addMapping("task", "id", Task.class);
		arp.addMapping("task_card", "id", TaskCard.class);
		arp.addMapping("task_supervise", "id", TaskSupervise.class);
	}
}

