package com.cnksi.kconf.model;

import com.cnksi.kcore.jfinal.model.BaseModel;
/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Role extends BaseModel<Role> {

	public static final Role me = new Role();


	@SuppressWarnings("rawtypes") 
 	@Override 
 	  protected Class getCls() {
		return this.getClass();
	}
}
